# Dependencies
markdown:         kramdown # redcarpet
highlighter:      rouge # pygments
plugins: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Ashley Yuan
# tagline:          "Ashley's Website"
description: |    
            University of Wisconsin - Madison
            CS Masters Student
            Formerly a 3D animator
baseurl:          https://ashleynanchiang.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
