# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ashley's Website
tagline:          'Ashley'
description:      "UW Madison CS Professional Master's student\n
                   3D animator in past life"
# url:              http://hyde.getpoole.com
baseurl:          https://ashleynanchiang.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         10

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
